from home.models import Addstudent

# Define a list of dummy data
dummy_data = ([
    {"name": "Mechahana Gupta", "mis": "222104133", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvay Sharma", "mis": "222104134", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Singh", "mis": "222104135", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechnvay Patel", "mis": "222104136", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharya Verma", "mis": "222104137", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharadhya Reddy", "mis": "222104138", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechbeer Kumar", "mis": "222104139", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechahil Tiwari", "mis": "222104140", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharohi Mishra", "mis": "222104141", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Jain", "mis": "222104142", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvika Shah", "mis": "222104143", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Deshmukh", "mis": "222104144", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Kumar", "mis": "222104145", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharadhya Singh", "mis": "222104146", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhya Verma", "mis": "222104147", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Reddy", "mis": "222104148", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvaita Patel", "mis": "222104149", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharnav Gupta", "mis": "222104150", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Sharma", "mis": "222104151", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvik Tiwari", "mis": "222104152", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechayansh Singh", "mis": "222104153", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhira Jain", "mis": "222104154", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadvika Verma", "mis": "222104155", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Reddy", "mis": "222104156", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharna Kumar", "mis": "222104157", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Shah", "mis": "222104158", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechayat Mishra", "mis": "222104159", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhya Patel", "mis": "222104160", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharush Verma", "mis": "222104161", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharohi Reddy", "mis": "222104162", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechaditya Jain", "mis": "222104163", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhira Tiwari", "mis": "222104164", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharadhya Shah", "mis": "222104165", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Kumar", "mis": "222104166", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Singh", "mis": "222104167", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechayansh Verma", "mis": "222104168", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvika Patel", "mis": "222104169", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharna Reddy", "mis": "222104170", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechaditya Tiwari", "mis": "222104171", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Shah", "mis": "222104172", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechahil Kumar", "mis": "222104173", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharohi Gupta", "mis": "222104174", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhya Singh", "mis": "222104175", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Patel", "mis": "222104176", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadit Tiwari", "mis": "222104177", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadya Verma", "mis": "222104178", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Reddy", "mis": "222104179", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Jain", "mis": "222104180", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharna Gupta", "mis": "222104181", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadvika Shah", "mis": "222104182", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Mishra", "mis": "222104183", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharadhya Tiwari", "mis": "222104184", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhira Patel", "mis": "222104185", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Verma", "mis": "222104186", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Reddy", "mis": "222104187", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvika Jain", "mis": "222104188", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharna Shah", "mis": "222104189", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadvika Kumar", "mis": "222104190", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Mishra", "mis": "222104191", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Shah", "mis": "222104192", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhya Tiwari", "mis": "222104193", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechaditya Gupta", "mis": "222104194", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Patel", "mis": "222104195", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharna Mishra", "mis": "222104196", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvay Shah", "mis": "222104197", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Kumar", "mis": "222104198", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhira Verma", "mis": "222104199", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharya Shah", "mis": "222104200", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharna Patel", "mis": "222104201", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharadhya Jain", "mis": "222104202", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadit Reddy", "mis": "222104203", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvik Mishra", "mis": "222104204", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhya Gupta", "mis": "222104205", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharna Tiwari", "mis": "222104206", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhya Verma", "mis": "222104207", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharyan Shah", "mis": "222104208", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvit Kumar", "mis": "222104209", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Jain", "mis": "222104210", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechanya Mishra", "mis": "222104222", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Shah", "mis": "222104212", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadhya Kumar", "mis": "222104213", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharadhya Tiwari", "mis": "222104214", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadya Patel", "mis": "222104215", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharav Verma", "mis": "222104216", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechdvaita Reddy", "mis": "222104217", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechadvik Patel", "mis": "222104218", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharya Mishra", "mis": "222104219", "branch": "Mechanical", "year": "TY"},
    {"name": "Mecharit Shah", "mis": "222104220", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechavya Gupta", "mis": "222104223", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechakshay Sharma", "mis": "222104224", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechajay Singh", "mis": "222104225", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechakriti Patel", "mis": "222104226", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechaditya Verma", "mis": "222104227", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechabhavika Reddy", "mis": "222104228", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechanirudh Jain", "mis": "222104229", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechamegha Tiwari", "mis": "222104230", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechaharsh Gupta", "mis": "222104231", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechabhumika Shah", "mis": "222104232", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechaarav Kumar", "mis": "222104233", "branch": "Mechanical", "year": "TY"},
    {"name": "Mechaparit Verma", "mis": "222104234", "branch": "Mechanical", "year": "TY"}
])


# Loop through the dummy data list and create instances
for data in dummy_data:
    Addstudent.objects.create(**data)

# Verify the data has been created
print("Dummy data added successfully!")
