# Generated by Django 5.0.4 on 2024-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mis', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
